### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by cyberbuddy-manas** [lazarnarcis/random-joke-generator#29]
Hi, I can improve the UI of the app if you want. I'll be using your code for my own project so in return I can at least help you by improving the UI. So @lazarnarcis  if you are active assign me this issue and we can work together!!

**Comment by lazarnarcis** [comment]
hi @cyberbuddy-manas . you can copy my code. it's public

**Comment by cyberbuddy-manas** [comment]
Great @lazarnarcis, will send pull request pretty soon!! Thanks for your help
